version: '2'

services:
  web:
    build: .
    volumes:
      - .:/app
    links:
      - "redis"
    ports:
      - "3000:8484"
    depends_on:
      - redis
  redis:
    image: redis:3.2.11
    volumes:
      - ./data:/data