version: '2'

services:
  web:
    build: .
    command: node server.js
    volumes:
      - .:/app
    links:
      - "redis"
    ports: 
      - "3000:8409"
    depends_on:
      - redis
  redis:
    image: redis:3.2.11
    volumes:
      - ./data:/data
