version: '2'

services:
  web:
    build: .
#    volumes:
#      - .:/usr/src/app
    links:
      - "redis"
    ports:
      - "3000:3000"
    command: node server.js
    depends_on:
      - redis
  redis:
    image: redis:3.2.11
    volumes:
      - ./data:/data
